"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Colors = void 0;
var Colors;
(function (Colors) {
    Colors["Black"] = "#000000";
    Colors["White"] = "#FFFFFF";
    Colors["Red"] = "#FF0000";
    Colors["Green"] = "#00FF00";
    Colors["Blue"] = "#0000FF";
    Colors["Yellow"] = "#FFFF00";
    Colors["Cyan"] = "#00FFFF";
    Colors["Magenta"] = "#FF00FF";
    Colors["Orange"] = "#FFA500";
    Colors["Purple"] = "#800080";
    Colors["Brown"] = "#A52A2A";
    Colors["Pink"] = "#FFC0CB";
    Colors["Lime"] = "#00FF00";
    Colors["Indigo"] = "#4B0082";
    Colors["Violet"] = "#EE82EE";
    Colors["Grey"] = "#808080";
    Colors["DarkGrey"] = "#A9A9A9";
    Colors["LightGrey"] = "#D3D3D3";
    Colors["Maroon"] = "#800000";
    Colors["Navy"] = "#000080";
    Colors["Olive"] = "#808000";
    Colors["Teal"] = "#008080";
    Colors["Silver"] = "#C0C0C0";
    Colors["Gold"] = "#FFD700";
})(Colors || (exports.Colors = Colors = {}));
